<a href="https://colab.research.google.com/github/gursewak-007/Machine-learning/blob/main/deep_learning_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!uname -a

Linux 0a99a71066b4 5.4.188+ #1 SMP Sun Apr 24 10:03:06 PDT 2022 x86_64 x86_64 x86_64 GNU/Linux


#iris dataset 

##data import

In [ ]:
from google.colab import files
import pandas as pd


In [ ]:
files.upload()

In [ ]:
!ls

Iris.csv  sample_data


In [ ]:
dataset=pd.read_csv('Iris.csv')

##dataset preprocessing

In [ ]:
%tensorflow_version 2.x
import tensorflow as tf
print(tf.version)

<module 'tensorflow._api.v2.version' from '/usr/local/lib/python3.7/dist-packages/tensorflow/_api/v2/version/__init__.py'>


In [ ]:
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
dataset.drop(["Id"],axis=1,inplace=True)

In [ ]:
display(dataset)

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
0              5.1           3.5            1.4           0.2     Iris-setosa
1              4.9           3.0            1.4           0.2     Iris-setosa
2              4.7           3.2            1.3           0.2     Iris-setosa
3              4.6           3.1            1.5           0.2     Iris-setosa
4              5.0           3.6            1.4           0.2     Iris-setosa
..             ...           ...            ...           ...             ...
145            6.7           3.0            5.2           2.3  Iris-virginica
146            6.3           2.5            5.0           1.9  Iris-virginica
147            6.5           3.0            5.2           2.0  Iris-virginica
148            6.2           3.4            5.4           2.3  Iris-virginica
149            5.9           3.0            5.1           1.8  Iris-virginica

[150 rows x 5 columns]

checking for categorical features



In [ ]:
data_type=dict(dataset.dtypes)
cat_cols=[]
for i in data_type:
  if data_type.get(i)=="object":
    cat_cols.append(i)

In [ ]:
dataset['Species']=dataset['Species'].astype('category')

dataset["Species_cat"] = dataset['Species'].cat.codes

dataset.drop(['Species'],axis=1,inplace=True)

In [ ]:
display(dataset)

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species_cat
0              5.1           3.5            1.4           0.2            0
1              4.9           3.0            1.4           0.2            0
2              4.7           3.2            1.3           0.2            0
3              4.6           3.1            1.5           0.2            0
4              5.0           3.6            1.4           0.2            0
..             ...           ...            ...           ...          ...
145            6.7           3.0            5.2           2.3            2
146            6.3           2.5            5.0           1.9            2
147            6.5           3.0            5.2           2.0            2
148            6.2           3.4            5.4           2.3            2
149            5.9           3.0            5.1           1.8            2

[150 rows x 5 columns]

##training and predicting

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import RobustScaler

from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras import layers
from tensorflow.keras.layers import Dense
from keras import backend as K

In [ ]:
df=dataset.copy()

In [ ]:
x = df.drop(['Species_cat'], axis=1)
y = pd.get_dummies(df['Species_cat']).values
#split the features and labels into  train and test data
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)
#rescale the data to be robust to outliers
scaler = RobustScaler()
scaler.fit(x_train)
x_train = scaler.transform(x_train)
x_test = scaler.transform(x_test)

In [ ]:
x_train.shape

(120, 4)

In [ ]:
model=Sequential([
    Dense(100,input_shape=(4,),activation='relu'),
    Dense(3,activation='sigmoid'),

])

In [ ]:
model.summary()

Model: "sequential_22"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_44 (Dense)            (None, 100)               500       
                                                                 
 dense_45 (Dense)            (None, 3)                 303       
                                                                 
Total params: 803
Trainable params: 803
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.compile(optimizer=tf.keras.optimizers.Adam(
    learning_rate=0.01),
    loss='binary_crossentropy',metrics='accuracy')

In [ ]:
model.fit(x_train,y_train,epochs=15,validation_split=0.2)

Epoch 1/15
3/3 [==============================] - 0s 57ms/step - loss: 0.0234 - accuracy: 0.9896 - val_loss: 0.0860 - val_accuracy: 0.9583
Epoch 2/15
3/3 [==============================] - 0s 28ms/step - loss: 0.0235 - accuracy: 0.9896 - val_loss: 0.0856 - val_accuracy: 0.9583
Epoch 3/15
3/3 [==============================] - 0s 27ms/step - loss: 0.0233 - accuracy: 0.9896 - val_loss: 0.0862 - val_accuracy: 0.9583
Epoch 4/15
3/3 [==============================] - 0s 34ms/step - loss: 0.0228 - accuracy: 0.9896 - val_loss: 0.0866 - val_accuracy: 0.9583
Epoch 5/15
3/3 [==============================] - 0s 48ms/step - loss: 0.0222 - accuracy: 0.9896 - val_loss: 0.0870 - val_accuracy: 0.9583
Epoch 6/15
3/3 [==============================] - 0s 36ms/step - loss: 0.0219 - accuracy: 0.9896 - val_loss: 0.0881 - val_accuracy: 0.9583
Epoch 7/15
3/3 [==============================] - 0s 29ms/step - loss: 0.0222 - accuracy: 0.9896 - val_loss: 0.0934 - val_accuracy: 0.9583
Epoch 8/15
3/3 [===========

In [ ]:
pred=model.predict(x_test)

In [ ]:
model.evaluate(x_test,y_test)

1/1 [==============================] - 0s 40ms/step - loss: 0.0181 - accuracy: 1.0000


[0.0180569589138031, 1.0]

In [ ]:
display(np.argmax(y_test,axis=1))

array([0, 1, 1, 0, 2, 1, 2, 0, 0, 2, 1, 0, 2, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       1, 0, 2, 1, 0, 0, 1, 2])

In [ ]:
display(np.argmax(pred,axis=1))

#bank dataset

##import dataset

In [ ]:
from google.colab import files

In [ ]:
files.upload()

Saving bank-data.csv to bank-data.csv


{'bank-data.csv': b'id,age,sex,region,income,married,children,car,save_act,current_act,mortgage,pep\nID12101,48,FEMALE,INNER_CITY,17546.0,NO,1,NO,NO,NO,NO,YES\nID12102,40,MALE,TOWN,30085.1,YES,3,YES,NO,YES,YES,NO\nID12103,51,FEMALE,INNER_CITY,16575.4,YES,0,YES,YES,YES,NO,NO\nID12104,23,FEMALE,TOWN,20375.4,YES,3,NO,NO,YES,NO,NO\nID12105,57,FEMALE,RURAL,50576.3,YES,0,NO,YES,NO,NO,NO\nID12106,57,FEMALE,TOWN,37869.6,YES,2,NO,YES,YES,NO,YES\nID12107,22,MALE,RURAL,8877.07,NO,0,NO,NO,YES,NO,YES\nID12108,58,MALE,TOWN,24946.6,YES,0,YES,YES,YES,NO,NO\nID12109,37,FEMALE,SUBURBAN,25304.3,YES,2,YES,NO,NO,NO,NO\nID12110,54,MALE,TOWN,24212.1,YES,2,YES,YES,YES,NO,NO\nID12111,66,FEMALE,TOWN,59803.9,YES,0,NO,YES,YES,NO,NO\nID12112,52,FEMALE,INNER_CITY,26658.8,NO,0,YES,YES,YES,YES,NO\nID12113,44,FEMALE,TOWN,15735.8,YES,1,NO,YES,YES,YES,YES\nID12114,66,FEMALE,TOWN,55204.7,YES,1,YES,YES,YES,YES,YES\nID12115,36,MALE,RURAL,19474.6,YES,0,NO,YES,YES,YES,NO\nID12116,38,FEMALE,INNER_CITY,22342.1,YES,0,YES,YES,YE

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
!ls

bank-data.csv  sample_data


In [ ]:
dataset=pd.read_csv("bank-data.csv")
dataset.drop(['id'],axis=1,inplace=True)

In [ ]:
dataset['sex']=dataset['sex'].astype('category')

In [ ]:
data_type=dict(dataset.dtypes)
cat_cols=[]
for i in data_type:
  if data_type.get(i)=="object":
    cat_cols.append(i)


In [ ]:
for i in cat_cols:
  dataset[i] = dataset[i].astype('category')
for i in cat_cols:
  dataset[f"{i}_cat"] = dataset[i].cat.codes
  dataset.drop(i,axis=1,inplace=True)

In [ ]:
display(dataset)

age    income  children  region_cat  married_cat  car_cat  save_act_cat  \
0     48  17546.00         1           0            0        0             0   
1     40  30085.10         3           3            1        1             0   
2     51  16575.40         0           0            1        1             1   
3     23  20375.40         3           3            1        0             0   
4     57  50576.30         0           1            1        0             1   
..   ...       ...       ...         ...          ...      ...           ...   
595   61  47025.00         2           0            0        1             1   
596   30   9672.25         0           0            1        1             1   
597   31  15976.30         0           3            1        1             1   
598   29  14711.80         0           0            1        0             1   
599   38  26671.60         0           3            0        1             0   

     current_act_cat  mortgage_cat  pep_cat  sex_cat  
0                  0             0        1        0  
1                  1             1        0        1  
2                  1             0        0        0  
3                  1             0        0        0  
4                  0             0        0        0  
..               ...           ...      ...      ...  
595                1             1        0        0  
596                1             0        0        0  
597                0             0        1        0  
598                0             1        0        1  
599                1             1        1        1  

[600 rows x 11 columns]

##split and scale dataset

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import RobustScaler

In [ ]:
df=dataset.copy()

In [ ]:
x = df.drop(['pep_cat'], axis=1)
# y=df['pep_cat']
y = pd.get_dummies(df['pep_cat']).values
#split the features and labels into  train and test data
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)
#rescale the data to be robust to outliers
scaler = RobustScaler()
scaler.fit(x_train)
x_train = scaler.transform(x_train)
x_test = scaler.transform(x_test)

##building model and predicting

In [ ]:
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras import layers
from tensorflow.keras.layers import Dense
from keras import backend as K
import joblib
from sklearn.metrics import classification_report


In [ ]:
x_train.shape

(480, 10)

In [ ]:
model=Sequential([
    Dense(40,input_shape=(10,),activation="relu"),
    Dense(20,activation='selu'),
    Dense(2,activation='sigmoid')
])

In [ ]:
480/40

12.0

In [ ]:
model.compile(optimizer=keras.optimizers.Adadelta(learning_rate=0.1),loss='log_cosh',metrics='accuracy')

In [ ]:
model.fit(x_train,y_train,epochs=10,validation_split=0.2,steps_per_epoch=48)

Epoch 1/10
48/48 [==============================] - 1s 8ms/step - loss: 0.0285 - accuracy: 0.9349 - val_loss: 0.0784 - val_accuracy: 0.7500
Epoch 2/10
48/48 [==============================] - 0s 5ms/step - loss: 0.0284 - accuracy: 0.9427 - val_loss: 0.0786 - val_accuracy: 0.7396
Epoch 3/10
48/48 [==============================] - 0s 4ms/step - loss: 0.0284 - accuracy: 0.9427 - val_loss: 0.0785 - val_accuracy: 0.7396
Epoch 4/10
48/48 [==============================] - 0s 6ms/step - loss: 0.0283 - accuracy: 0.9427 - val_loss: 0.0786 - val_accuracy: 0.7396
Epoch 5/10
48/48 [==============================] - 0s 5ms/step - loss: 0.0282 - accuracy: 0.9401 - val_loss: 0.0787 - val_accuracy: 0.7396
Epoch 6/10
48/48 [==============================] - 0s 6ms/step - loss: 0.0281 - accuracy: 0.9427 - val_loss: 0.0785 - val_accuracy: 0.7500
Epoch 7/10
48/48 [==============================] - 0s 5ms/step - loss: 0.0281 - accuracy: 0.9427 - val_loss: 0.0786 - val_accuracy: 0.7500
Epoch 8/10
48/48 [==

In [ ]:
joblib.dump(model,'new84.pkl')

INFO:tensorflow:Assets written to: ram://45092601-b2da-4b62-b9c2-7a38fe919a5b/assets


['new84.pkl']

In [ ]:
pred=model.predict(x_test)

In [ ]:
model.evaluate(x_test,y_test)

4/4 [==============================] - 0s 4ms/step - loss: 0.0692 - accuracy: 0.8250


[0.06921011954545975, 0.824999988079071]

In [ ]:
print(classification_report(np.argmax(y_test,axis=1),np.argmax(pred,axis=1)))

              precision    recall  f1-score   support

           0       0.82      0.91      0.86        66
           1       0.87      0.76      0.81        54

    accuracy                           0.84       120
   macro avg       0.85      0.83      0.84       120
weighted avg       0.84      0.84      0.84       120



In [ ]:
model=joblib.load('new84.pkl')

In [ ]:
display(np.argmax(y_test,axis=1))

array([0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0,
       0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1])

In [ ]:
display(np.argmax(pred,axis=1))

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0,
       0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0,
       0, 1, 0, 1, 1, 1, 1, 1, 0, 1])